PROGRAM BALISTICA
	IMPLICIT NONE
	INTEGER :: R
	REAL :: X, DX, DDX, Y, DY, DDY, G=9.8E0, B, ANGG, PI=3.14159265, V, T, H, ANG, MODV
	
	OPEN (UNIT=10,FILE="BAL_TEMPOESPX.txt")
	OPEN (UNIT=11,FILE="BAL_TEMPOESPY.txt")
	OPEN (UNIT=12,FILE="BAL_ESPAÇOXY.txt")
	OPEN (UNIT=13,FILE="BAL_TEMPOVELX.txt")
	OPEN (UNIT=14,FILE="BAL_TEMPOVELY.txt")
	
	PRINT*, "VOCE GOSTARIA DE UTILIZAR A RESISTENCIA DO AR? (B=4*10^(-5)) ; 0 = SIM ; 1 = NAO"
	READ*, R
	
	IF (R==0) THEN
		B=4E-5
		ELSE
		B=0
	END IF
	
	PRINT*, "DIGITE O ANGULO DE INCLINAÇAO DO CANHAO (GRAUS)"
	READ*, ANGG
	
	ANG=(ANGG*PI)/180
	
	PRINT*, "DIGITE A VELOCIDADE DE LANÇAMENTO DA BALA(m/s)"
	READ*, V
	
	Y=0
	X=0
	DX=V*COS(ANG)
	DY=V*SIN(ANG)
	
	H=0.01
	
	DO
	
		MODV=SQRT((DX**2)+(DY**2))
			
		T=T+H
		X=X+H*DX
		Y=Y+H*DY
		DY=DY-H*(G+B*DY*MODV)
		DX=DX-H*(B*DX*MODV)
		
		WRITE (10,*) T,X ! FORMATO LIVRE
		WRITE (11,*) T,Y ! FORMATO LIVRE
		WRITE (12,*) X,Y ! FORMATO LIVRE
		WRITE (13,*) T,DX ! FORMATO LIVRE
		WRITE (14,*) T,DY ! FORMATO LIVRE
		
		IF (Y<=0) EXIT		
		
		PRINT*, T, X, Y, DX, DY
		
	END DO
	
END PROGRAM
